### ISSUE TITLE
"More about open source" missing nouns and adjectives!

### ISSUE THREAD

**Issue by gilhooleyd** [princeton-2015-1/princeton-2015-1.github.io#1]
The "more about open source" section appears to be missing some nouns and adjectives. What an adjective noun that is!

Can you find us some adjectives and nouns? Any adjectives and nouns will do.

Make sure to find all of them!

**Comment by jijessicam** [comment]
I'll do this!

**Comment by hypotext** [comment]
Done by @jijessicam!
